version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: web-postgres
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      # - .:/var/lib/postgresql/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d dbname -U dashori"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
        - .env
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: web-backend
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy 
    networks:
      - mynetwork

#   nginx:
#     image: nginx:1.24
#     container_name: web-nginx
#     env_file:
#       - .env
#     networks:
#       - mynetwork
#     ports:
#       - ${NGINX_EXTERNAL_PORT}:${NGINX_PORT}
#     volumes:
#       - ./logs/nginx:/var/log/nginx
#       - ./nginx/nginx.conf:/nginx.conf.template
#     depends_on:
#       - backend
#       - postgres

networks:
  mynetwork:
#     driver: bridge
